//! Unified error type for the runits crate.
//!
//! All fallible public APIs return `Result<_, RUnitsError>`. The enum covers
//! every failure mode the user might hit: an unknown unit name, incompatible
//! dimensions during conversion, or a malformed input string.

use thiserror::Error;

/// Every failure mode across the crate, surfaced as one enum.
///
/// Display impls are generated by `thiserror` from the `#[error("…")]`
/// attributes; each message is crafted to stand on its own when printed
/// from `main()` on exit.
#[derive(Debug, Error)]
pub enum RUnitsError {
    /// The parser couldn't resolve a unit name against the database.
    /// Carries fuzzy suggestions when available.
    #[error("{}", format_unknown_unit(.name, .suggestions))]
    UnknownUnit {
        name: String,
        suggestions: Vec<String>,
    },

    /// Two units couldn't be converted because their dimensions differ
    /// (e.g., meters → kilograms).
    #[error("cannot convert '{from}' to '{to}': incompatible dimensions ({from_dim} vs {to_dim})")]
    IncompatibleDimensions {
        from: String,
        to: String,
        from_dim: String,
        to_dim: String,
    },

    /// Affine units (e.g., temperature scales) cannot form compound units.
    #[error(
        "cannot compose affine unit '{0}' in multiplication/division (temperature units cannot form compound units)"
    )]
    AffineComposition(String),

    /// Input didn't match the quantity grammar. The inner pest error
    /// carries a source-span pointer for precise user feedback. Boxed so
    /// `RUnitsError` stays small (clippy's `result_large_err` guidance).
    #[error("parse error\n{0}")]
    Parse(#[from] Box<pest::error::Error<crate::parser::Rule>>),
}

fn format_unknown_unit(name: &str, suggestions: &[String]) -> String {
    if suggestions.is_empty() {
        format!("unknown unit: '{name}'")
    } else {
        format!(
            "unknown unit: '{name}'. Did you mean: {}?",
            suggestions.join(", ")
        )
    }
}
